### ISSUE TITLE
[BUG][QR] Not display modal notification when scanning invalid QR code

### ISSUE THREAD

**Issue by minh-tranchi** [ncc-erp/ncc-erp-ams-fe#36]
**AR:** When scanning an invalid QR code, an error has occurred
**ER:** Should display a modal notification for scanning invalid QR code

![Image](https://github.com/user-attachments/assets/62eacc7d-693b-4a11-8838-45b04fec2666)

![Image](https://github.com/user-attachments/assets/f0c61537-ea6d-484c-80f0-cfda9caf2739)

**Comment by thucaothidieu** [comment]
**Testing failed on dev**
Not display modal notification when scanning invalid QR code
