### ISSUE TITLE
[BUG][QR] Should disable Bên trên/Bên dưới field when Mã thiết bị checkbox is unchecked

### ISSUE THREAD

**Issue by minh-tranchi** [ncc-erp/ncc-erp-ams-fe#37]
![Image](https://github.com/user-attachments/assets/6caed2bc-68a8-4a15-bcbc-c60ff36adf83)

**Comment by thucaothidieu** [comment]
**BUG:**
ER: 
- Should hide Bên trên/Bên dưới field when unchecking Mã thiết bị checkbox
- Should show Bên trên/Bên dưới field when checking Mã thiết bị checkbox
![Image](https://github.com/user-attachments/assets/e659d81c-4556-4e44-9416-a2afdeaea071)
