### ISSUE TITLE
[BUG][RESPONSIVE] Responsive issues on laptop/desktop views

### ISSUE THREAD

**Issue by minh-tranchi** [ncc-erp/ncc-erp-ams-fe#41]
**Screens: 
1280 x 800 
1440 x 900
1366 x 768
1920 x 1080 (only issue Click on `Thêm mới` button)**

- Click on `Thêm mới` button

![Image](https://github.com/user-attachments/assets/84ad51cb-80ac-4936-9b32-acf7d2a596d3)

- Actions:

`Xem chi tiết`

![Image](https://github.com/user-attachments/assets/fc675ea8-693a-40af-9df0-6fc09d4ccb3f)

`Clone`

![Image](https://github.com/user-attachments/assets/bc5f05a3-0cf2-481a-b8ef-3543b89eb1f5)

`Chỉnh sửa
`

![Image](https://github.com/user-attachments/assets/41e59269-dd8e-4476-b71d-6f97bcdd6ff9)

- `Kho` > `Chỉnh sửa`

![Image](https://github.com/user-attachments/assets/14ad2812-c58f-4d2f-a3a3-f1206cb8a3e5)

- `Người dùng` > `Chỉnh sửa`

![Image](https://github.com/user-attachments/assets/f8ea47bc-367f-4d1d-8294-5445f6e257b5)

**Screens:
1280 x 800 
1366 x 768**

Select 10 properties in the table > Click on `In mã QR` button

![Image](https://github.com/user-attachments/assets/192f57b6-dd67-489e-8bb5-478bd1b8fdbe)

**Comment by thucaothidieu** [comment]
Testing failed on dev
**Screens:
1280 x 800
1440 x 900
1366 x 768**
![Image](https://github.com/user-attachments/assets/8a32de38-bf17-4481-8226-62e0bce641d5)


**Screens:
1280 x 800
1366 x 768**

Select 10 properties in the table > Click on In mã QR button
![Image](https://github.com/user-attachments/assets/34207c04-f3c8-4657-9f07-a65776724934)

**Screen 1366 x 768**
![Image](https://github.com/user-attachments/assets/6b7f2d08-e48f-4886-8af2-12a171c42e30)
