### ISSUE TITLE
[BUG][RESPONSIVE] Mobile view not responsive

### ISSUE THREAD

**Issue by minh-tranchi** [ncc-erp/ncc-erp-ams-fe#42]
![Image](https://github.com/user-attachments/assets/9b4538b5-944d-4eb6-b1fd-37184072eaa3)

![Image](https://github.com/user-attachments/assets/8f8645d4-4a53-471b-99b5-5b8016775b3f)

**Comment by thucaothidieu** [comment]
**Testing failed on dev**

![Image](https://github.com/user-attachments/assets/c42b4238-57a0-4316-b954-9a8c0462a3a3)
![Image](https://github.com/user-attachments/assets/affa1cf7-4a3e-4dc0-b3f3-8c104ef069e1)
![Image](https://github.com/user-attachments/assets/3c31466f-fbcc-4a8d-bb47-85f33c9c72bd)
